version: "3.9"

networks:
  SOURCEDOUT:
    driver: bridge
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "443:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - SOURCEDOUT
  php:
    build: .
    image: sourceodut-php
    container_name: SOURCEDOUT_php
    volumes:
      - ..:/app:cached
      - ../storage/app/public:/app/public/storage:cached
    working_dir: /app
    ports:
      - "9090:9000"
    networks:
      - SOURCEDOUT
  nginx:
    image: nginx:stable-alpine
    container_name: SOURCEDOUT_nginx
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./nginx.web.conf:/etc/nginx/conf.d/default.conf
      - ..:/app
      - ../storage/app/public:/app/public/storage:cached
    working_dir: /app
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=sourcedout.localhost
      - VIRTUAL_PORT=80
    networks:
      - SOURCEDOUT
  mysql:
    image: mariadb:10.4
    container_name: SOURCEDOUT_mysql
    volumes:
      - ../.database:/var/lib/mysql:delegated
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - SOURCEDOUT
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: SOURCEDOUT_phpMyAdmin
    ports:
      - "8082:80"
    expose:
      - "80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 200M
      VIRTUAL_HOST: "phpmyadmin.sourcedout.localhost"
      VIRTUAL_PORT: 80
    networks:
      - SOURCEDOUT
  redis:
    image: redis:6.2.6-alpine3.14
    container_name: SOURCEDOUT_redis
    command: redis-server --appendonly yes
    volumes:
      - ../.redis:/data
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - SOURCEDOUT